import { FarmerProfile, BuyerProfile, ProduceListing, DemandRequirement, CropPriceIntelligence, DealOffer } from './types';

export const MOCK_CROPS = ['Sugarcane', 'White Maize', 'Avocados', 'Citrus Oranges', 'Sorghum', 'Cassava'];

export const INITIAL_FARMERS: FarmerProfile[] = [
  {
    id: 'f1',
    name: 'Muzi Shongwe',
    country: 'Eswatini',
    currency: 'SZL',
    location: 'Manzini, Eswatini',
    farmSize: 45,
    cropTypes: ['Sugarcane', 'White Maize'],
    contact: '+268 7602-1234',
    rating: 4.8,
    ratingCount: 3,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    password: 'password123',
    registeredDate: '2025-01-10',
    approved: true,
    regNumber: 'SZ-FARM-1002',
    docName: 'certified_grower_license.pdf',
    emailVerified: true,
    preferredPaymentMethod: 'mobile_money',
    reviews: [
      { id: 'rev1', buyerName: 'Eswatini Sugar Association', rating: 5, comment: 'Excellent sugarcane quality, very professional cooperative partner.', date: '2026-05-15' },
      { id: 'rev2', buyerName: 'SADC Food Processors', rating: 4, comment: 'Good quality white maize. Delivery was on time.', date: '2026-06-01' },
      { id: 'rev3', buyerName: 'Maputo Fresh Distributors', rating: 5.4, comment: 'Great service and reliable communication.', date: '2026-06-10' }
    ]
  },
  {
    id: 'f2',
    name: 'Temaswati Simelane',
    country: 'Eswatini',
    currency: 'SZL',
    location: 'Hhohho Region, Eswatini',
    farmSize: 12,
    cropTypes: ['Avocados', 'Citrus Oranges'],
    contact: '+268 7811-5678',
    rating: 4.9,
    ratingCount: 2,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    password: 'password123',
    registeredDate: '2024-11-05',
    approved: true,
    regNumber: 'SZ-FARM-2005',
    docName: 'eswatini_organic_cert.pdf',
    emailVerified: true,
    preferredPaymentMethod: 'mobile_money',
    reviews: [
      { id: 'rev4', buyerName: 'Maputo Fresh Distributors', rating: 5, comment: 'Organic avocados are premium quality. Highly recommended!', date: '2026-05-20' },
      { id: 'rev5', buyerName: 'SADC Food Processors', rating: 4.8, comment: 'Juicy citrus oranges, will buy again next season.', date: '2026-06-12' }
    ]
  },
  {
    id: 'f3',
    name: 'Linda Ndlovu',
    country: 'Eswatini',
    currency: 'SZL',
    location: 'Shiselweni Region, Eswatini',
    farmSize: 80,
    cropTypes: ['White Maize', 'Sorghum', 'Cassava'],
    contact: '+268 7933-9012',
    rating: 4.5,
    ratingCount: 1,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    password: 'password123',
    registeredDate: '2025-03-22',
    approved: true,
    regNumber: 'SZ-FARM-3008',
    docName: 'shiselweni_cooperative_permit.pdf',
    emailVerified: true,
    preferredPaymentMethod: 'bank_transfer',
    reviews: [
      { id: 'rev6', buyerName: 'Eswatini Sugar Association', rating: 4.5, comment: 'Very large quantity capacity. Sorghum standard quality was good.', date: '2026-06-05' }
    ]
  },
];

export const INITIAL_BUYERS: BuyerProfile[] = [
  {
    id: 'b1',
    company: 'Eswatini Sugar Association',
    category: 'Wholesale',
    contact: 'sourcing@eswatinisugar.co.sz',
    country: 'Eswatini',
    currency: 'SZL',
    location: 'Mbabane, Eswatini',
    password: 'password123',
    registeredDate: '2025-02-15',
    approved: true,
    regNumber: 'SZ-TIN-88901',
    docName: 'sugar_assoc_charter.pdf',
    emailVerified: true,
    preferredPaymentMethod: 'bank_transfer',
  },
  {
    id: 'b2',
    company: 'SADC Food Processors',
    category: 'Processing',
    contact: 'procurement@sadcfoods.co.za',
    country: 'South Africa',
    currency: 'ZAR',
    location: 'Johannesburg, South Africa',
    password: 'password123',
    registeredDate: '2024-09-12',
    approved: true,
    regNumber: 'ZA-REG-55201',
    docName: 'sadc_import_clearance.pdf',
    emailVerified: true,
    preferredPaymentMethod: 'card',
  },
  {
    id: 'b3',
    company: 'Maputo Fresh Distributors',
    category: 'Retail',
    contact: 'purchasing@maputofresh.co.mz',
    country: 'Mozambique',
    currency: 'MZN',
    location: 'Maputo, Mozambique',
    password: 'password123',
    registeredDate: '2025-04-01',
    approved: true,
    regNumber: 'MZ-TIN-44019',
    docName: 'maputo_retail_license.pdf',
    emailVerified: true,
  },
  {
    id: 'b4',
    company: 'Ezulwini Food Exporters',
    category: 'Exporter',
    contact: 'trade@ezulwinifood.com',
    country: 'Eswatini',
    currency: 'SZL',
    location: 'Ezulwini, Eswatini',
    password: 'password123',
    registeredDate: '2025-05-10',
    approved: true,
    regNumber: 'SZ-TIN-77302',
    docName: 'ezulwini_export_charter.pdf',
    emailVerified: true,
  },
];

export const INITIAL_LISTINGS: ProduceListing[] = [
  {
    id: 'l1',
    farmerId: 'f1',
    farmerName: 'Muzi Shongwe',
    farmerRating: 4.8,
    crop: 'Sugarcane',
    quantity: 25000,
    price: 0.18,
    grade: 'A',
    location: 'Manzini, Eswatini',
    dateListed: '2026-06-18',
  },
  {
    id: 'l2',
    farmerId: 'f1',
    farmerName: 'Muzi Shongwe',
    farmerRating: 4.8,
    crop: 'White Maize',
    quantity: 8000,
    price: 0.32,
    grade: 'B',
    location: 'Manzini, Eswatini',
    dateListed: '2026-06-19',
  },
  {
    id: 'l3',
    farmerId: 'f2',
    farmerName: 'Temaswati Simelane',
    farmerRating: 4.9,
    crop: 'Avocados',
    quantity: 3500,
    price: 1.15,
    grade: 'A',
    location: 'Hhohho Region, Eswatini',
    dateListed: '2026-06-20',
  },
  {
    id: 'l4',
    farmerId: 'f2',
    farmerName: 'Temaswati Simelane',
    farmerRating: 4.9,
    crop: 'Citrus Oranges',
    quantity: 12000,
    price: 0.55,
    grade: 'A',
    location: 'Hhohho Region, Eswatini',
    dateListed: '2026-06-20',
  },
  {
    id: 'l5',
    farmerId: 'f3',
    farmerName: 'Linda Ndlovu',
    farmerRating: 4.5,
    crop: 'Sorghum',
    quantity: 9000,
    price: 0.28,
    grade: 'A',
    location: 'Shiselweni Region, Eswatini',
    dateListed: '2026-06-17',
  },
];

export const INITIAL_DEMANDS: DemandRequirement[] = [
  {
    id: 'd1',
    buyerId: 'b1',
    buyerName: 'Eswatini Sugar Association',
    crop: 'Sugarcane',
    quantity: 20000,
    budget: 0.22,
    deadline: '2026-06-30',
    location: 'Mbabane, Eswatini',
    datePosted: '2026-06-19',
  },
  {
    id: 'd2',
    buyerId: 'b2',
    buyerName: 'SADC Food Processors',
    crop: 'White Maize',
    quantity: 15000,
    budget: 0.35,
    deadline: '2026-07-15',
    location: 'Johannesburg, South Africa',
    datePosted: '2026-06-20',
  },
  {
    id: 'd3',
    buyerId: 'b3',
    buyerName: 'Maputo Fresh Distributors',
    crop: 'Avocados',
    quantity: 3000,
    budget: 1.30,
    deadline: '2026-07-10',
    location: 'Maputo, Mozambique',
    datePosted: '2026-06-21',
  },
];

export const INITIAL_DEALS: DealOffer[] = [
  {
    id: 'deal1',
    buyerId: 'b1',
    buyerName: 'Eswatini Sugar Association',
    farmerId: 'f1',
    farmerName: 'Muzi Shongwe',
    listingId: 'l1',
    crop: 'Sugarcane',
    quantity: 10000,
    price: 0.18,
    totalAmount: 1800,
    status: 'accepted',
    deliveryDate: '2026-06-25',
    deliveryStatus: 'scheduled',
    ratingGiven: false,
    dateCreated: '2026-06-20',
    paymentStatus: 'unpaid',
  },
];


export const CROP_PRICE_INTELLIGENCE: Record<string, CropPriceIntelligence> = {
  Sugarcane: {
    crop: 'Sugarcane',
    minPrice: 0.12,
    maxPrice: 0.24,
    avgPrice: 0.17,
    currentDemandIndex: 8,
    forecastDemandIndex: 9,
    forecastPriceTrend: 'up',
    recommendedPrice: 0.19,
    marketInsights: 'Eswatini sugarcane exports face high demand from SADC refineries and European markets. Local milling operations are expanding. Pricing trends upwards due to global sugar deficit forecasts.',
    history: [
      { month: 'Jan', price: 0.14, demandIndex: 6 },
      { month: 'Feb', price: 0.15, demandIndex: 7 },
      { month: 'Mar', price: 0.16, demandIndex: 7 },
      { month: 'Apr', price: 0.17, demandIndex: 8 },
      { month: 'May', price: 0.17, demandIndex: 8 },
      { month: 'Jun', price: 0.18, demandIndex: 8 },
    ],
  },
  'White Maize': {
    crop: 'White Maize',
    minPrice: 0.22,
    maxPrice: 0.38,
    avgPrice: 0.30,
    currentDemandIndex: 6,
    forecastDemandIndex: 8,
    forecastPriceTrend: 'up',
    recommendedPrice: 0.34,
    marketInsights: 'El Niño weather patterns have restricted maize yields in parts of Southern Africa, driving import demand. Eswatini and South African buyers are competing for local grain reserves. Prices are projected to peak in late winter.',
    history: [
      { month: 'Jan', price: 0.28, demandIndex: 5 },
      { month: 'Feb', price: 0.29, demandIndex: 6 },
      { month: 'Mar', price: 0.30, demandIndex: 6 },
      { month: 'Apr', price: 0.31, demandIndex: 7 },
      { month: 'May', price: 0.32, demandIndex: 7 },
      { month: 'Jun', price: 0.32, demandIndex: 8 },
    ],
  },
  Avocados: {
    crop: 'Avocados',
    minPrice: 0.85,
    maxPrice: 1.45,
    avgPrice: 1.10,
    currentDemandIndex: 7,
    forecastDemandIndex: 9,
    forecastPriceTrend: 'up',
    recommendedPrice: 1.20,
    marketInsights: 'High-quality avocados from Hhohho are seeing intensive interest from South African wholesalers for export to Europe. Strong regional SADC consumption and limited supply support high prices.',
    history: [
      { month: 'Jan', price: 0.95, demandIndex: 6 },
      { month: 'Feb', price: 1.00, demandIndex: 7 },
      { month: 'Mar', price: 1.05, demandIndex: 7 },
      { month: 'Apr', price: 1.10, demandIndex: 8 },
      { month: 'May', price: 1.12, demandIndex: 8 },
      { month: 'Jun', price: 1.15, demandIndex: 9 },
    ],
  },
  'Citrus Oranges': {
    crop: 'Citrus Oranges',
    minPrice: 0.40,
    maxPrice: 0.70,
    avgPrice: 0.52,
    currentDemandIndex: 6,
    forecastDemandIndex: 6,
    forecastPriceTrend: 'stable',
    recommendedPrice: 0.54,
    marketInsights: 'Citrus growers in Eswatini and Mpumalanga report normal yields. Strong demand from juice processing facilities in South Africa provides stable pricing.',
    history: [
      { month: 'Jan', price: 0.50, demandIndex: 5 },
      { month: 'Feb', price: 0.51, demandIndex: 5 },
      { month: 'Mar', price: 0.52, demandIndex: 6 },
      { month: 'Apr', price: 0.53, demandIndex: 6 },
      { month: 'May', price: 0.54, demandIndex: 6 },
      { month: 'Jun', price: 0.55, demandIndex: 6 },
    ],
  },
  Sorghum: {
    crop: 'Sorghum',
    minPrice: 0.20,
    maxPrice: 0.32,
    avgPrice: 0.26,
    currentDemandIndex: 5,
    forecastDemandIndex: 5,
    forecastPriceTrend: 'stable',
    recommendedPrice: 0.27,
    marketInsights: 'Drought-tolerant sorghum yields are steady in Shiselweni. SADC beverage manufacturers maintain a steady demand stream. Market remains balanced with stable seasonal pricing.',
    history: [
      { month: 'Jan', price: 0.25, demandIndex: 5 },
      { month: 'Feb', price: 0.25, demandIndex: 5 },
      { month: 'Mar', price: 0.26, demandIndex: 5 },
      { month: 'Apr', price: 0.26, demandIndex: 5 },
      { month: 'May', price: 0.27, demandIndex: 5 },
      { month: 'Jun', price: 0.28, demandIndex: 5 },
    ],
  },
  Cassava: {
    crop: 'Cassava',
    minPrice: 0.15,
    maxPrice: 0.28,
    avgPrice: 0.21,
    currentDemandIndex: 7,
    forecastDemandIndex: 6,
    forecastPriceTrend: 'down',
    recommendedPrice: 0.20,
    marketInsights: 'Abundant harvests in Mozambique and parts of Eswatini have increased supply in border markets. Starch processing demand remains steady, but pricing pressure is mounting due to local surpluses.',
    history: [
      { month: 'Jan', price: 0.23, demandIndex: 7 },
      { month: 'Feb', price: 0.22, demandIndex: 7 },
      { month: 'Mar', price: 0.22, demandIndex: 7 },
      { month: 'Apr', price: 0.21, demandIndex: 6 },
      { month: 'May', price: 0.21, demandIndex: 6 },
      { month: 'Jun', price: 0.21, demandIndex: 6 },
    ],
  },
};
